unbind-key C-b
bind r source-file ~/.tmux.conf
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

set -g prefix C-a
setw -g mode-keys vi
set -g mouse on
set -g allow-rename off
set -g renumber-windows on
set -g status-left-length 85
set -g status-left "(#S)" # (session name) window_index/num_windows
set -g status-right "%H:%M %d-%b-%Y"
set -g status-justify centre
set -g base-index 1 # start window index at 1
set -g default-terminal xterm-256color
set -g history-limit 100000
# TODO
# set -g set-titles on
# set -g set-titles-string "#P"
# set -g status-bg black
# set -g status-fg green


## Use vim keybindings in copy mode
# https://www.rockyourcode.com/copy-and-paste-in-tmux/
set-option -g mouse on
setw -g mode-keys vi
set-option -s set-clipboard off
bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X rectangle-toggle
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'pbcopy -se c -i'
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel 'pbcopy -se c -i'
# Now you can enter copy mode normally with CTRL+B and [.
# Navigate the copy mode with vi-like-key bindings (u for up, d for down, etc.)
# Hit v to start copying.
# Press y or Enter to copy the text into the tmux buffer. This automatically cancels copy mode.
# Paste into the buffer with <prefix>+P (make sure that it’s uppercase P).
# Or alternatively, use the mouse to copy text after you’ve entered copy mode.
# The above commands use xclip, a Linux command line tool for X11. You can replace xclip -se c -i with a platform-specific command like pbcopy (MacOS) or wl-copy (Wayland).
